# Population
POPULATION_SIZE = 3
GENERATIONS = 3

# Elitism
ELITE_SIZE = 1

# Selection
TOURNAMENT_SIZE = 2

# Crossover
CROSSOVER_PROBABILITY = 0.8
UNIFORM_CROSSOVER_INDPB = 0.5

# Mutation
MUTATION_PROBABILITY = 0.8
MUTATION_GENE_PROBABILITY = 0.1